export default class Reminder{
	id: number;
	isComplete: boolean;

	constructor(public title: string){
		this.id = Date.now()  //should really be id generated by the db, but this works
		this.isComplete = false
	}
}